services:
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_EMAILJS_SERVICE_ID=${VITE_EMAILJS_SERVICE_ID}
        - VITE_EMAILJS_TEMPLATE_ID=${VITE_EMAILJS_TEMPLATE_ID}
        - VITE_EMAILJS_PUBLIC_KEY=${VITE_EMAILJS_PUBLIC_KEY}
    ports:
      - "5173:5173"

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_SSL=${DB_SSL}
      - DB_USER=${DB_USER}
      - NODE_ENV=${NODE_ENV}
      - TZ=${TZ}
      - JWT_SECRET=${JWT_SECRET}
      - VIDEOSDK_API_KEY=${VIDEOSDK_API_KEY}
      - VIDEOSDK_SECRET_KEY=${VIDEOSDK_SECRET_KEY}
    command: sh -c "npx typeorm-ts-node-commonjs migration:run -d src/config/data-source.ts && node dist/main.js"
